-- C COLORS
local hl = vim.api.nvim_set_hl
hl(0, "Normal", { bg = "#FFFFFF", fg = "#000000"})
hl(0, "@annotation.c", { fg = "#646464", bold = true })
hl(0, "@comment.c", { fg = "#646464", bg = "#d5d5d5", bold = true })
hl(0, "@comment.documentation.c", { fg = "#727171", bold = true })
hl(0, "@comment.todo.c", { fg = "#a80b00", bg = "#e9ffe7", bold = true })
hl(0, "@constant.c", { fg = "#0079da", bold = true, italic = true })
hl(0, "@constant.builtin.c", { fg = "#0079da", bold = true, italic = true })
hl(0, "@constant.macro.c", { fg = "#0079da", bold = true, italic = true })
hl(0, "@variable.c", { fg = "#000000", bold = true, sp = "#ff0000"  })
hl(0, "@variable.builtin.c", { fg = "#000000", italic = true })
hl(0, "@variable.parameter.c", { fg = "#000000", italic = true })
hl(0, "@variable.parameter.builtin.c", { fg = "#000000", italic = true })
hl(0, "@variable.member.c", { fg = "#c0c0c0", bold = true })
hl(0, "@variable.local.c", { fg = "#000000", italic = true })
hl(0, "@namespace.c", { fg = "#88005d", bold = true })
hl(0, "@function.c", { fg = "#000000", italic = true })
hl(0, "@function.builtin.c", { fg = "#0059ff", italic = true })
hl(0, "@function.call.c", { fg = "#000000", italic = true })
hl(0, "@function.macro.c", { fg = "#000000", italic = true })
hl(0, "@function.method.c", { fg = "#000000", italic = true })
hl(0, "@function.method.call.c", { fg = "#000000", italic = true })
hl(0, "@constructor.c", { fg = "#000000", bold = true })
hl(0, "@operator.c", { fg = "#88005d", bold = true })
hl(0, "@keyword.c", { fg = "#e66e19", bold = true })
hl(0, "@keyword.coroutine.c", { fg = "#e66e19", bold = true })
hl(0, "@keyword.function.c", { fg = "#e66e19", bold = true })
hl(0, "@keyword.operator.c", { fg = "#e66e19", bold = true })
hl(0, "@keyword.import.c", { fg = "#e66e19", bold = true })
hl(0, "@keyword.type.c", { fg = "#e66e19", bold = true })
hl(0, "@keyword.modifier.c", { fg = "#e66e19", bold = true })
hl(0, "@keyword.repeat.c", { fg = "#e66e19", bold = true })
hl(0, "@keyword.return.c", { fg = "#e66e19", bold = true })
hl(0, "@keyword.debug.c", { fg = "#e66e19", bold = true })
hl(0, "@keyword.exception.c", { fg = "#e66e19", bold = true })
hl(0, "@keyword.conditional.c", { fg = "#e66e19", bold = true })
hl(0, "@keyword.conditional.ternary.c", { fg = "#e66e19", bold = true })
hl(0, "@keyword.directive.c", { fg = "#e66e19", bold = true })
hl(0, "@keyword.directive.define.c", { fg = "#e66e19", bold = true })
hl(0, "@type.c", { fg = "#a65c12", bold = true, italic = true })
hl(0, "@type.builtin.c", { fg = "#a65c12", bold = true, italic = true })
hl(0, "@type.definition.c", { fg = "#a65c12", bold = true, italic = true })
hl(0, "@type.alias.c", { fg = "#a65c12", bold = true, italic = true })
hl(0, "@attribute.c", { fg = "#646464", bold = true })
hl(0, "@attribute.builtin.c", { fg = "#646464", bold = true })
hl(0, "@property.c", { fg = "#140096", bold = true, italic = true })
hl(0, "@punctuation.delimiter.c", { fg = "#000000" })
hl(0, "@punctuation.bracket.c", { fg = "#99ccbb", bold = true })
hl(0, "@punctuation.special.c", { fg = "#000000" })
hl(0, "@string.c", { fg = "#8a8a8a", italic = true })
hl(0, "@string.documentation.c", { fg = "#8a8a8a", italic = true })
hl(0, "@string.regexp.c", { fg = "#8a8a8a", italic = true })
hl(0, "@string.escape.c", { fg = "#8a8a8a", italic = true })
hl(0, "@string.special.c", { fg = "#8a8a8a", italic = true })
hl(0, "@string.special.symbol.c", { fg = "#8a8a8a", italic = true })
hl(0, "@string.special.url.c", { fg = "#8a8a8a", italic = true })
hl(0, "@string.special.path.c", { fg = "#8a8a8a", italic = true })
hl(0, "@character.c", { fg = "#8a8a8a", italic = true })
hl(0, "@character.special.c", { fg = "#8a8a8a", italic = true })
hl(0, "@boolean.c", { fg = "#a80b00", bold = true })
hl(0, "@number.c", { fg = "#0079da" })
hl(0, "@number.float.c", { fg = "#0079da" })
hl(0, "@markup.strong.c", { fg = "#000000", bold = true })
hl(0, "@markup.italic.c", { fg = "#000000", bold = true, italic = true })
hl(0, "@markup.strikethrough.c", { fg = "#000000", bold = true, italic = true })
hl(0, "@markup.underline.c", { fg = "#000000", bold = true, italic = true })
hl(0, "@markup.heading.c", { fg = "#e66e19", bold = true })
hl(0, "@markup.heading.1.c", { fg = "#e66e19", bold = true })
hl(0, "@markup.heading.2.c", { fg = "#e66e19", bold = true })
hl(0, "@markup.heading.3.c", { fg = "#e66e19", bold = true })
hl(0, "@markup.heading.4.c", { fg = "#e66e19", bold = true })
hl(0, "@markup.heading.5.c", { fg = "#e66e19", bold = true })
hl(0, "@markup.heading.6.c", { fg = "#e66e19", bold = true })
hl(0, "@markup.quote.c", { fg = "#727171", bold = true })
hl(0, "@markup.math.c", { fg = "#8a8a8a", bold = true })
hl(0, "@markup.link.c", { fg = "#258bff", bold = true })
hl(0, "@markup.link.label.c", { fg = "#258bff", bold = true })
hl(0, "@markup.link.url.c", { fg = "#258bff", bold = true })
hl(0, "@markup.raw.c", { fg = "#000000", italic = true })
hl(0, "@markup.raw.block.c", { fg = "#000000", italic = true })
hl(0, "@markup.list.c", { fg = "#646464" })
hl(0, "@markup.list.checked.c", { fg = "#00a80b" })
hl(0, "@markup.list.unchecked.c", { fg = "#00a80b" })
hl(0, "@diff.plus.c", { fg = "#00a80b" })
hl(0, "@diff.minus.c", { fg = "#ff0000" })
hl(0, "@diff.delta.c", { fg = "#88005d", bold = true })
hl(0, "@tag.c", { fg = "#000000" })
hl(0, "@tag.builtin.c", { fg = "#258bff", bold = true })
hl(0, "@tag.attribute.c", { fg = "#646464", bold = true })
hl(0, "@tag.delimiter.c", { fg = "#99ccbb" })
hl(0, "@macro.c", { fg = "#000000", italic = true })
hl(0, "@toml.key.c", { fg = "#e66e19", bold = true })
hl(0, "@search.c", { fg = "#000000", bg = "#e9ffe7" })
