-- Clear existing highlights and reset syntax
vim.cmd("highlight clear")
vim.cmd("syntax reset")

-- Custom todo highlight
vim.api.nvim_set_hl(0, "@comment.todo", { fg = "#FF0000", bold = true })
-- Make sure floating windows follow the same style
vim.api.nvim_set_hl(0, 'NormalFloat', { bg = '#353b44', fg = '#cdcfd2' })
vim.api.nvim_set_hl(0, 'FloatBorder', { bg = '#353b44', fg = '#000000' })
-- Lsp error/warning/info highlights
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#745454", bg = "#e5d2d2", bold = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = "#FF9999" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#747454", bg = "#e5e5d2", bold = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = "#FFD1A6" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#545474", bg = "#d2d2e5", bold = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = "#99CCFF" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#548484", bg = "#d2e9e9", bold = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = "#CCE5FF" })

local hl = vim.api.nvim_set_hl
hl(0, "Normal", { bg = "#252b34", fg = "#cdcfd2" })
hl(0, "@annotation", { fg = "#ffb373", bold = true })
hl(0, "@comment", { fg = "#cdcfd2", bg = "#252b34", bold = true })
hl(0, "@comment.documentation", { fg = "#cdcfd2", bold = true })
hl(0, "@comment.todo", { fg = "#63c259", bg = "#292f39", bold = true })
hl(0, "@comment-asterisk", { fg = "#abc9ff", bg = "#292f39", bold = true })
hl(0, "@comment-minus", { fg = "#b2ccd6", bg = "#292f39", bold = true })
hl(0, "@constant", { fg = "#a1ffe0", bold = true, italic = true })
hl(0, "@constant.builtin", { fg = "#a1ffe0", bold = true, italic = true })
hl(0, "@constant.macro", { fg = "#a1ffe0", bold = true, italic = true })
hl(0, "@variable", { fg = "#cdcfd2", bold = true, sp = "#ff7085" })
hl(0, "@variable.builtin", { fg = "#cdcfd2", italic = true })
hl(0, "@variable.parameter", { fg = "#ffffff", italic = true })
hl(0, "@variable.parameter.builtin", { fg = "#ffffff", italic = true })
hl(0, "@variable.member", { fg = "#bce0ff", bold = true })
hl(0, "@variable.local", { fg = "#cdcfd2", italic = true })
hl(0, "@namespace", { fg = "#42ffc2", bold = true })
hl(0, "@function", { fg = "#57b3ff", italic = true })
hl(0, "@function.builtin", { fg = "#57b3ff", italic = true })
hl(0, "@function.call", { fg = "#57b3ff", italic = true })
hl(0, "@function.macro", { fg = "#57b3ff", italic = true })
hl(0, "@function.method", { fg = "#57b3ff", italic = true })
hl(0, "@function.method.call", { fg = "#57b3ff", italic = true })
hl(0, "@constructor", { fg = "#42ffc2", bold = true })
hl(0, "@operator", { fg = "#abc9ff", bold = true })
hl(0, "@keyword", { fg = "#ff7085", bold = true })
hl(0, "@keyword.coroutine", { fg = "#ff7085", bold = true })
hl(0, "@keyword.function", { fg = "#ff7085", bold = true })
hl(0, "@keyword.operator", { fg = "#ff7085", bold = true })
hl(0, "@keyword.import", { fg = "#ff7085", bold = true })
hl(0, "@keyword.type", { fg = "#ff7085", bold = true })
hl(0, "@keyword.modifier", { fg = "#ff7085", bold = true })
hl(0, "@keyword.repeat", { fg = "#ff7085", bold = true })
hl(0, "@keyword.return", { fg = "#ff7085", bold = true })
hl(0, "@keyword.debug", { fg = "#ff7085", bold = true })
hl(0, "@keyword.exception", { fg = "#ff7085", bold = true })
hl(0, "@keyword.conditional", { fg = "#ff8ccc", bold = true })
hl(0, "@keyword.conditional.ternary", { fg = "#ff8ccc", bold = true })
hl(0, "@keyword.directive", { fg = "#ff7085", bold = true })
hl(0, "@keyword.directive.define", { fg = "#ff7085", bold = true })
hl(0, "@type", { fg = "#42ffc2", bold = true, italic = true })
hl(0, "@type.builtin", { fg = "#8fffdb", bold = true, italic = true })
hl(0, "@type.definition", { fg = "#42ffc2", bold = true, italic = true })
hl(0, "@type.alias", { fg = "#42ffc2", bold = true, italic = true })
hl(0, "@attribute", { fg = "#cdcfd2", bold = true })
hl(0, "@attribute.builtin", { fg = "#cdcfd2", bold = true })
hl(0, "@property", { fg = "#bce0ff", bold = true, italic = true })
hl(0, "@punctuation.delimiter", { fg = "#abc9ff" })
hl(0, "@punctuation.bracket", { fg = "#abc9ff", bold = true })
hl(0, "@punctuation.special", { fg = "#abc9ff" })
hl(0, "@string", { fg = "#ffeda1", italic = true })
hl(0, "@string.documentation", { fg = "#ffeda1", italic = true })
hl(0, "@string.regexp", { fg = "#89ddff", italic = true })
hl(0, "@string.escape", { fg = "#ffeda1", italic = true })
hl(0, "@string.special", { fg = "#ffeda1", italic = true })
hl(0, "@string.special.symbol", { fg = "#ffeda1", italic = true })
hl(0, "@string.special.url", { fg = "#ffeda1", italic = true })
hl(0, "@string.special.path", { fg = "#ffeda1", italic = true })
hl(0, "@character", { fg = "#ffeda1", italic = true })
hl(0, "@character.special", { fg = "#ffeda1", italic = true })
hl(0, "@boolean", { fg = "#ff7085", bold = true })
hl(0, "@number", { fg = "#a1ffe0" })
hl(0, "@number.float", { fg = "#a1ffe0" })
hl(0, "@markup.strong", { fg = "#cdcfd2", bold = true })
hl(0, "@markup.italic", { fg = "#cdcfd2", bold = true, italic = true })
hl(0, "@markup.strikethrough", { fg = "#cdcfd2", bold = true, italic = true })
hl(0, "@markup.underline", { fg = "#cdcfd2", bold = true, italic = true })
hl(0, "@markup.heading", { fg = "#ff7085", bold = true })
hl(0, "@markup.heading.1", { fg = "#ff7085", bold = true })
hl(0, "@markup.heading.2", { fg = "#ff7085", bold = true })
hl(0, "@markup.heading.3", { fg = "#ff7085", bold = true })
hl(0, "@markup.heading.4", { fg = "#ff7085", bold = true })
hl(0, "@markup.heading.5", { fg = "#ff7085", bold = true })
hl(0, "@markup.heading.6", { fg = "#ff7085", bold = true })
hl(0, "@markup.quote", { fg = "#cdcfd2", bold = true })
hl(0, "@markup.math", { fg = "#ffeda1", bold = true })
hl(0, "@markup.link", { fg = "#57b3ff", bold = true })
hl(0, "@markup.link.label", { fg = "#57b3ff", bold = true })
hl(0, "@markup.link.url", { fg = "#57b3ff", bold = true })
hl(0, "@markup.raw", { fg = "#cdcfd2", italic = true })
hl(0, "@markup.raw.block", { fg = "#cdcfd2", italic = true })
hl(0, "@markup.list", { fg = "#cdcfd2" })
hl(0, "@markup.list.checked", { fg = "#42ffc2" })
hl(0, "@markup.list.unchecked", { fg = "#42ffc2" })
hl(0, "@diff.plus", { fg = "#42ffc2" })
hl(0, "@diff.minus", { fg = "#ff786b" })
hl(0, "@diff.delta", { fg = "#42ffc2", bold = true })
hl(0, "@tag", { fg = "#cdcfd2" })
hl(0, "@tag.builtin", { fg = "#57b3ff", bold = true })
hl(0, "@tag.attribute", { fg = "#cdcfd2", bold = true })
hl(0, "@tag.delimiter", { fg = "#abc9ff" })
hl(0, "@macro", { fg = "#cdcfd2", italic = true })
hl(0, "@toml.key", { fg = "#ff7085", bold = true })
hl(0, "@search", { fg = "#cdcfd2", bg = "#292f39" })

