local hl = vim.api.nvim_set_hl

-- NAYSAYER THEME
hl(0, "Normal",            { bg = "#062329", fg = "#d1b897" })
hl(0, "@comment.c",        { fg = "#44b340" })
hl(0, "@constant.c",       { fg = "#7ad0c6" })
hl(0, "@variable.c",       { fg = "#c1d1e3" })
--hl(0, "@function.body.c",  { bg = "#0b3335" })
hl(0, "@function.name.c",  { fg = "#ffffff" })
hl(0, "@property.c",       { fg = "#c1d1e3" })
hl(0, "@function.c",       { fg = "#ffffff" })
hl(0, "@keyword.c",        { fg = "#ffffff" })
hl(0, "@type.c",           { fg = "#d1b897" })
hl(0, "@string.c",         { fg = "#2ec90c" })
hl(0, "@character.c",      { fg = "#d1b897" })
hl(0, "@number.c",         { fg = "#7ad0c6" })
hl(0, "@operator.c",       { fg = "#ffffff", bold = true })

-- Map naysayer colors to terminal ANSI slots.
hl(0, "NormalFloat",       { bg = "#032026", fg = "#d1b897" })
vim.g.terminal_color_0  = "#163339" -- Black       (theme background)
vim.g.terminal_color_1  = "#44b340" -- Red         (comment green, fits as a "muted red")
vim.g.terminal_color_2  = "#2ec90c" -- Green       (string green)
vim.g.terminal_color_3  = "#d1b897" -- Yellow      (type/character)
vim.g.terminal_color_4  = "#7ad0c6" -- Blue        (constant/number)
vim.g.terminal_color_5  = "#ffffff" -- Magenta     (function/keyword/operator)
vim.g.terminal_color_6  = "#c1d1e3" -- Cyan        (property/variable)
vim.g.terminal_color_7  = "#d1b897" -- White       (same as yellow/type for bright white)
vim.g.terminal_color_8  = "#0b3335" -- Bright Black (slightly lighter bg)
vim.g.terminal_color_9  = "#44b340" -- Bright Red   (same as normal comment green)
vim.g.terminal_color_10 = "#2ec90c" -- Bright Green (string green)
vim.g.terminal_color_11 = "#d1b897" -- Bright Yellow (type)
vim.g.terminal_color_12 = "#7ad0c6" -- Bright Blue   (constant)
vim.g.terminal_color_13 = "#ffffff" -- Bright Magenta (function/keyword)
vim.g.terminal_color_14 = "#c1d1e3" -- Bright Cyan    (variable)
vim.g.terminal_color_15 = "#ffffff" -- Bright White   (pure white)
